#! /usr/bin/bash

function vardef {
        micstatus=$(fuser /dev/snd/pcmC0D0c)
}>/dev/null 2>&1

vardef

if [ "$micstatus" == "" ]; then
	echo ""
elif [ "$micstatus" != "" ]; then
	echo "SPY!"
else
	echo "MAYBE"
fi
