#! /usr/bin/bash

CYAN='\033[0;36m'
PURPLE="\033[0;95m"
NC='\033[0m'

function cyan {
       printf "${CYAN}$@${NC}\n"
}

function purple {
       printf "${PURPLE}$@${NC}\n"
}

function idkwhat {
	recstatus=$(fuser /dev/snd/pcmC0D0c)
}>/dev/null 2>&1

function checker {
	idkwhat
	if [ "$recstatus" == "" ]; then
	       echo "none"
	elif [ "$recstatus" != "" ]; then
	       echo "YES"
		echo "Output by fuser: " $(fuser /dev/snd/pcmC0D0c)
	else
	       echo "MAYBE"
		echo "Output by fuser: " $(fuser /dev/snd/pcmC0D0c)
	fi
	idkwhat
}

function main {
	idkwhat

	echo -e $(cyan "This is the output by fuser")
	echo -e $(cyan "Press CTRL+C or CTRL+Z to quit")

	while :
	do
		checker
		sleep 1
	done
}

main
