#! /usr/bin/bash

timesnowrn=$(date +%H)

function set-wallpaper (){
	swaymsg output "*" bg "$1" fill
	echo "Current wallpaper: " "$1"
}

if [[ "$1" == "--time-according" || "$1" == "-ta" ]]
then
	if [[ "$timesnowrn" < "18" || "$timesnowrn" > "06" ]]
	then
		wallp="$HOME/wallpapers/night/"$(ls $HOME/wallpapers/night | shuf -n 1)
		echo "Setting a Dark Mode Wallpaper..."
		set-wallpaper "$wallp"

	else
		wallp="$HOME/wallpapers/best/"$(ls $HOME/wallpapers/best | shuf -n 1)
		echo "Setting a Light Mode Wallpaper..."
		set-wallpaper "$wallp"
	fi

elif [[ "$1" == "--dark-mode" || "$1" == "-d" ]]
then
	wallp="$HOME/wallpapers/night/"$(ls $HOME/wallpapers/night | shuf -n 1)
	echo "Setting a Dark Mode Wallpaper..."
	set-wallpaper "$wallp"

elif [[ "$1" == "--light-mode" || "$1" == "-l" ]]
then
	wallp="$HOME/wallpapers/main/"$(ls $HOME/wallpapers/main | shuf -n 1)
	echo "Setting a Light Mode Wallpaper..."
	set-wallpaper "$wallp"

elif [[ "$1" == "" ]]
then
	wallp="$HOME/wallpapers/main/"$(ls $HOME/wallpapers/main | shuf -n 1)
	echo "Setting a Normal Wallpaper..."
	set-wallpaper "$wallp"

else
	echo "This is not a valid command. Look at the source code for available options because we are lazy."

fi
